version: '3'
services:
  adhoc-nginx:
    image: trzl/portfolio:adhoc-react.1
    container_name: adhoc-nginx
    restart: unless-stopped
  reverseproxy:
    image: trzl/portfolio:adhoc-proxy.1
    container_name: adhoc-proxy
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    depends_on:
      - adhoc-nginx
    environment:
      VIRTUAL_HOST: adhoc.tbrownkcdev.com
      LETSENCRYPT_HOST: adhoc.tbrownkcdev.com
      LETSENCRYPT_EMAIL: brownty47@gmail.com
networks:
  default:
    external:
      name: webproxy
